ervices:
    client:
      container_name: habit_dev_client
      build: ./client
      image: habit_client
      ports: 
        - 8080:8080
      working_dir: /code
      volumes:
        - type: bind
          source: ./client
          target: /code
      command: [ "http-server" ]
    api:
      container_name: habit_dev_api
      ports: 
        - 3000:3000
      environment: 
        - PGUSER=habit
        - PGHOST=db
        - PGPASSWORD=habitpass
        - PGDATABASE=habit_test
        - PGPORT=5432
        - NODE_ENV=test
      depends_on:
        - db
      command: bash -c "npm install && npm run seedDev && npm run dev"
  
    db:
      container_name: habit_dev_db
      volumes:
        - "dbdata:/var/lib/postgresql/data"
      environment: 
        - POSTGRES_DB=habit_db
        - POSTGRES_USER=habit
        - POSTGRES_PASSWORD=habitpass
  volumes:
    dbdata:
  networks: 
    default:
      name: habit_api